### ISSUE TITLE
More control over BRF output required

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#103]
Do what I described in https://github.com/snaekobbi/pipeline-mod-dedicon/issues/21#issuecomment-200851328.

File format is already an existing concept in BrailleUtils.

**Comment by bertfrees** [comment]
@dkager: Have a look at what I did on the file-format branch: https://github.com/daisy/pipeline-mod-braille/compare/file-format.

Basically I just moved the code for creating a `BRFWriter` based on the options `table`, `line-breaks`, etc. from `PEF2TextStep` to `ConfigurableFileFormat`. The advantage is that `PEF2TextStep` got much more generic now because you can use it with any existing or custom implementation of `FileFormat`. FileFormats are searched based on a query, just like we do with Tables, BrailleTranslators, etc. The main implementation of `FileFormatProvider` is called `BrailleUtilsFileFormatCatalog`. It supports both `(format:<id>)` and `(embosser:<id>)` and the syntax for specifying a table is `(table:<id>)` or `(locale:<locale>)`. The other implementation is `ConfigurableFileFormat$Provider` which currently supports the features `table`, `locale`, `line-breaks`, `page-breaks` and `pad`.

Will you write the functionality to split into several files per volume? Like we said, to keep things simple we won't put this functionality in FileFormat for now, but handle it on a higher level and feed individual volume PEFs to the FileFormat.

**Comment by dkager** [comment]
I think splitting has to be a separate XProc step, taking the generated PEF as input and splitting it into multiple PEFs with given name. This might mean extending PEFFileSplitter a bit if we want padded numbers in the filenames, but maybe we don’t need that. I will inquire at Dedicon.

Also, the split PEFs all need to be passed to the BRF step. I have little experience with XProc so don’t know how hard that would be.

Whatever we do, I don’t want to manually parse the PEF. BrailleUtils seems to be very good at that already.

**Comment by bertfrees** [comment]
A separate XProc step for splitting a PEF is more complicated, but doable. For uniformity with other similar steps, the `pef:split` step would probably take a PEF document, would have an option `target-dir` and probably some other options to specify the name and numbering scheme, and it would have two output ports `fileset.out` and `in-memory.out`. (The document on port `fileset` is in a special Pipeline-specific format that lists all the files. `in-memory` may contain the files loaded into memory, but doesn't have to).

I don't know if you'll manage to do this by yourself. Maybe you can start out and if you need help with the fileset stuff I can help you.

Padding numbers can be added to PEFFileSplitter but could be done outside as well.

**Comment by dkager** [comment]
Yes, that seems overly complicated. I’d rather have something as simple as BRFWriter that works tomorrow (and as a bonus is more easily understood by novices like me). But if not an XProc step, what then?

**Comment by bertfrees** [comment]
You could have some additional options directly on `pef:store` for specifying whether and how to split the PEF and/or BRF. That would remove the fileset complexity.

**Comment by dkager** [comment]
OK, I’ll try to load pef-core and/or mod-dedicon into Eclipse and see what I can get working. :)

**Comment by bertfrees** [comment]
Note that you need to build https://github.com/brailleapps/braille-utils.api/pull/1 and https://github.com/joeha480/brailleutils/pull/71 first.

**Comment by bertfrees** [comment]
https://github.com/snaekobbi/pipeline-mod-dedicon/issues/21 lists the new options we ended up with in `pef:store`:

- `brf-dir-href`: directory in which to store the BRF files (replaces `brf-href`)
- `brf-name-pattern`: the name pattern for multiple volumes. "{}" is replaced by the volume number. if empty, then the PEF is not split
- `brf-single-volume-name`: the name for a single volume (without the extension)
- `brf-number-width`: the width of the volume number. if 0, then the volume number is not padded with zeroes
- `brf-file-format`: query for selecting BRF file format

Existing option:
- `brf-table`

A problem we have now is that the interaction between the `file-format` and `table` options is tricky. `table` can be meant for the BRF and/or the PEF preview. The way it currently works is that when `file-format` is specified in `pef:store` it is used, and `table` is ignored because it could otherwise conflict (see [store.xpl](https://github.com/snaekobbi/pipeline-mod-braille/blob/3abfdb11ec867b2866df8bc6cb3541c6d447c622/pipeline-braille-utils/pef-utils/pef-utils/src/main/resources/xml/store.xpl)). (And because in `px:dtbook-to-pef.store` a "locale" feature is always automatically added to `file-format`, it means `table` is always ignored.)

One solution is to only ignore `table` in `pef:store` if it causes a conflict (and possibly show a warning).

The other solution is to disallow specifying a `table` that conflicts with `file-format`, however I'm not sure we can do that. The file format might be used directly for printing, but the mapping might not be what people are used to reading. Also, what if in the future we support including several file formats at once (just an idea)? Finally, not all file formats necessarily need to be based on a table. (They could even be binary blobs in theory.)

A third possibility is to split up the `ascii-table` option into `brf-table`/`file-format-table` and `preview-table`.

A fourth possibility is to not even use `table` for selecting a file format table, instead relying only on the `file-format` option only. The downside of this is that the syntax for selecting a table differs in the two cases PEF preview vs. BRF ("nested" queries are not possible).

- [ ] To do: either fix or create a new ticket for it.

Until this is fixed, always specify the file format solely in the `file-format` query (solution 4.), e.g. by including a `(table:<id>)` feature.
