### ISSUE TITLE
-include-obfl option should work even when OBFL to PEF conversion fails

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#124]

**Comment by bertfrees** [comment]
I have accomplished this by adding a output port called `validation-status` which outputs a document of the format http://daisy.github.io/pipeline/wiki/ValidationStatusXML.

But now I have two questions:

1. I'm using the validation status format but this has nothing to do with validation. Could we generalize this from `d:validation-status` to `d:status?`. Similarly, could we generalize the job state `VALIDATION_FAIL`  to `FAIL`?

2. Shouldn't the engine find the validation-status port based on the media-type of the port (`application/vnd.pipeline.status+xml`) and not based on the name? I thought this was the case already but apparently it's not.

**Comment by bertfrees** [comment]
@josteinaj Currently the web UI says "Validation fails" when it receives the VALIDATION_FAIL status. If we generalize it to FAIL, how do we convey to the web UI the information that it was validation that failed? Is this simply a matter of presenting the right error messages and/or reports?

**Comment by josteinaj** [comment]
Yeah we can provide a report saying "validation failed" on the report port.
