### ISSUE TITLE
Push tags for v1.9.15 and v1.9.16

### ISSUE THREAD

**Issue by rdeltour** [daisy/pipeline-mod-braille#134]
The latest release [shown on GitHub](https://github.com/daisy/pipeline-mod-braille/releases) is `v1.9.14`, can you push the tags @bertfrees ?

```
$ git push --tags
```

**Comment by bertfrees** [comment]
Done

**Comment by bertfrees** [comment]
- https://github.com/daisy/pipeline-mod-braille/releases/tag/v1.9.15
- https://github.com/daisy/pipeline-mod-braille/releases/tag/v1.9.16
