### ISSUE TITLE
Improve stability

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#135]
Basically this means to solve the startup issue: Some services fail to start up correctly when the server is launched, and this happens randomly.

The suspicion is that this has something to do with OSGi, and the hope is that getting rid of OSGi (https://github.com/daisy/pipeline-tasks/issues/31) will either solve it, or throw some light on the issue.

**EDIT**: It could also be that there is a bug in the OSGi framework. In that case the issue could be fixed by updating to a newer version. This would be preferable over removing OSGi.

To do:
- [x] reproduce with v1.10
- [x] update OSGi framework
- [ ] ~~get rid of OSGi~~

**Comment by bertfrees** [comment]
Updating some OSGi libraries seems to have fixed the issue. You can never be sure of course, but I haven't reproduced the launch issue since.

**Comment by rdeltour** [comment]
@bertfrees I think this can be closed
