### ISSUE TITLE
Remove default-stylesheet option to avoid confusion

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#34]
The `default-stylesheet` option is for overriding the default style sheet that is always loaded before any other style sheets. Custom style sheets should be loaded by embedding them in the input XML or linking to them from the XML. Because this is causing confusion I think it's better to just drop the option, and to control the default style sheet it on a per script basis. This means you won't be able to prevent the default style sheet as defined by the script to load, however if needed you can always import a `reset.css` file.

**Comment by josteinaj** [comment]
sounds good
