### ISSUE TITLE
Adapt ASCII ouput (BRF) to locale and/or make it configurable

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#47]
The ASCII table can be made configurable with a feature in the `transform` option called `ascii-table`, e.g. `(ascii-table:de)` or `(ascii-table:"sbs.dis")` for example. If no feature is specified, the system should choose a reasonable default. Also, a custom formatter may set a specific ASCII table.

The way I would implement this is by adding a metadata field to the PEF header:

```xml
<dp2:ascii-table xmlns:dp2="http://www.daisy.org/ns/pipeline">...</dp2:ascii:table>
```

The value could be in CSS query format, or could be a simple ID.

**Comment by dkager** [comment]
For the reasonable default, `xml:lang` or the `locale` transform query could be used.

**Comment by bertfrees** [comment]
This was done in https://github.com/daisy/pipeline-mod-braille/pull/56 & https://github.com/snaekobbi/pipeline-mod-braille/issues/56.

There are still the issues https://github.com/daisy/pipeline-mod-braille/issues/75 and https://github.com/joeha480/brailleutils/issues/66.

But this one can be closed.
